import type { User, Question, Answer, Comment, Topic } from "@/types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Priya Sharma",
    email: "priya@example.com",
    avatar: "/professional-woman.png",
    bio: "Software Engineer at Google | IIT Delhi Alumni",
    reputation: 2850,
  },
  {
    id: "2",
    name: "Rahul Kumar",
    email: "rahul@example.com",
    avatar: "/man-developer.png",
    bio: "Entrepreneur | Startup Mentor | Ex-McKinsey",
    reputation: 1890,
  },
  {
    id: "3",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    avatar: "/woman-designer.png",
    bio: "Travel Blogger | Digital Nomad | 50+ countries visited",
    reputation: 3200,
  },
  {
    id: "4",
    name: "Dr. Amit Patel",
    email: "amit@example.com",
    avatar: "/caring-doctor.png",
    bio: "Cardiologist | Health & Wellness Advocate",
    reputation: 4100,
  },
  {
    id: "5",
    name: "Neha Gupta",
    email: "neha@example.com",
    avatar: "/diverse-classroom-teacher.png",
    bio: "English Teacher | Education Consultant",
    reputation: 1650,
  },
]

export const mockQuestions: Question[] = [
  {
    id: "1",
    title: "क्या IIT JEE की तैयारी 12वीं के साथ-साथ करना सही है?",
    content:
      "मैं 12वीं में हूं और JEE की तैयारी कर रहा हूं। क्या school के साथ-साथ JEE की तैयारी करना सही रहेगा या फिर drop लेना चाहिए? कृपया अपने अनुभव साझा करें।",
    authorId: "5",
    author: mockUsers[4],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    tags: ["education", "jee", "career", "hindi"],
    upvotes: 156,
    downvotes: 8,
    answerCount: 12,
    topicId: "2",
  },
  {
    id: "2",
    title: "What are some life lessons you wish you had learned earlier?",
    content:
      "I'm 25 and feeling like I'm behind in life. What are some important life lessons that you wish someone had told you when you were younger? Looking for genuine advice from people who have been through different phases of life.",
    authorId: "2",
    author: mockUsers[1],
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
    tags: ["life-advice", "personal-development", "wisdom"],
    upvotes: 284,
    downvotes: 12,
    answerCount: 23,
    topicId: "9",
  },
  {
    id: "3",
    title: "भारत में startup शुरू करने के लिए क्या-क्या चाहिए?",
    content:
      "मैं एक tech startup शुरू करना चाहता हूं लेकिन मुझे नहीं पता कि कहां से शुरुआत करूं। Legal requirements, funding, team building - सब कुछ confusing लग रहा है। कोई practical advice दे सकता है?",
    authorId: "1",
    author: mockUsers[0],
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    tags: ["startup", "entrepreneurship", "business", "hindi"],
    upvotes: 198,
    downvotes: 15,
    answerCount: 18,
    topicId: "5",
  },
  {
    id: "4",
    title: "How do you deal with toxic family members?",
    content:
      "I have family members who are constantly negative, critical, and emotionally draining. I love them but their behavior is affecting my mental health. How do you set boundaries with family while still maintaining relationships?",
    authorId: "3",
    author: mockUsers[2],
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
    tags: ["family", "relationships", "mental-health", "boundaries"],
    upvotes: 342,
    downvotes: 23,
    answerCount: 31,
    topicId: "3",
  },
  {
    id: "5",
    title: "क्या arranged marriage आज के time में सही है?",
    content:
      "मैं 28 साल का हूं और मेरे parents arranged marriage के लिए pressure डाल रहे हैं। मैं confused हूं कि क्या यह सही approach है या फिर love marriage का wait करना चाहिए। आपके क्या विचार हैं?",
    authorId: "4",
    author: mockUsers[3],
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
    tags: ["marriage", "relationships", "culture", "hindi"],
    upvotes: 267,
    downvotes: 45,
    answerCount: 28,
    topicId: "3",
  },
  {
    id: "6",
    title: "What's the best way to learn programming as a complete beginner?",
    content:
      "I'm 30 years old and want to switch careers to software development. I have zero programming experience. What's the most effective way to start learning? Should I go for a bootcamp, online courses, or self-study?",
    authorId: "5",
    author: mockUsers[4],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    tags: ["programming", "career-change", "learning", "beginner"],
    upvotes: 189,
    downvotes: 7,
    answerCount: 22,
    topicId: "1",
  },
]

export const mockAnswers: Answer[] = [
  {
    id: "1",
    content:
      "मैंने भी 12वीं के साथ JEE की तैयारी की थी और IIT Delhi में admission मिला था। मेरी सलाह है कि अगर आप disciplined हैं और time management अच्छी है तो साथ-साथ करें। Drop year में बहुत pressure होता है और guarantee नहीं है कि result बेहतर आएगा। School के साथ करने से आपके पास backup भी रहता है।",
    questionId: "1",
    authorId: "1",
    author: mockUsers[0],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    upvotes: 89,
    downvotes: 3,
    isAccepted: true,
  },
  {
    id: "2",
    content:
      "1. Start investing early, even small amounts compound over time.\n2. Your health is your wealth - don't neglect exercise and mental health.\n3. Learn to say 'no' - your time is precious.\n4. Build genuine relationships, not just networks.\n5. Failure is not the opposite of success, it's part of it.\n6. Don't compare your behind-the-scenes with others' highlight reels.\n7. Learn a skill that can make you money independently.",
    questionId: "2",
    authorId: "3",
    author: mockUsers[2],
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
    upvotes: 156,
    downvotes: 8,
    isAccepted: true,
  },
  {
    id: "3",
    content:
      "Startup शुरू करने के लिए सबसे पहले:\n1. अपना idea validate करें - customers से बात करें\n2. MVP (Minimum Viable Product) बनाएं\n3. Company registration करें (Private Limited recommended)\n4. GST registration करें\n5. Bank account खोलें\n6. Co-founder ढूंढें जो आपके skills को complement करे\n7. Angel investors या VCs से मिलने से पहले traction दिखाएं\n\nSबसे important बात - पहले product बनाएं, फिर funding के बारे में सोचें।",
    questionId: "3",
    authorId: "2",
    author: mockUsers[1],
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
    upvotes: 124,
    downvotes: 6,
    isAccepted: true,
  },
  {
    id: "4",
    content:
      "I've been through this. Here's what worked for me:\n\n1. Set clear boundaries and stick to them\n2. Limit your exposure - shorter visits, less frequent calls\n3. Don't try to change them, focus on changing your response\n4. Practice the 'gray rock' method - be polite but boring\n5. Build a strong support system outside the family\n6. Consider therapy to process your feelings\n7. Remember: you can love someone from a distance\n\nIt's okay to prioritize your mental health over family expectations.",
    questionId: "4",
    authorId: "4",
    author: mockUsers[3],
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
    upvotes: 203,
    downvotes: 12,
    isAccepted: false,
  },
  {
    id: "5",
    content:
      "दोनों approaches के अपने फायदे हैं। Arranged marriage में families involved होती हैं जो stability देता है, लेकिन compatibility का risk रहता है। Love marriage में emotional connection पहले से है लेकिन family acceptance का issue हो सकता है।\n\nMेरी सलाह है कि आप अपने parents से खुलकर बात करें। Maybe आप arranged meetings को dating की तरह approach कर सकते हैं - pressure नहीं, बस जानने के लिए। Right person मिले तो कहीं से भी मिले, important यह है कि आप comfortable feel करें।",
    questionId: "5",
    authorId: "1",
    author: mockUsers[0],
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
    upvotes: 145,
    downvotes: 18,
    isAccepted: false,
  },
  {
    id: "6",
    content:
      "As someone who switched to tech at 32, here's my roadmap:\n\n1. **Start with fundamentals**: Choose Python or JavaScript as your first language\n2. **Free resources first**: freeCodeCamp, Codecademy, YouTube tutorials\n3. **Build projects**: Start with simple ones, gradually increase complexity\n4. **Join communities**: Reddit r/learnprogramming, Discord servers, local meetups\n5. **Consider a bootcamp** only after you've tried self-learning for 2-3 months\n6. **Create a portfolio**: GitHub with your projects\n7. **Network**: Attend tech events, connect with developers on LinkedIn\n\nAge is just a number in tech. Focus on consistency over intensity.",
    questionId: "6",
    authorId: "2",
    author: mockUsers[1],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    upvotes: 167,
    downvotes: 4,
    isAccepted: true,
  },
]

export const mockComments: Comment[] = [
  {
    id: "1",
    content: "Great advice! I'm also preparing for JEE and this gives me confidence to continue with school.",
    answerId: "1",
    authorId: "2",
    author: mockUsers[1],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    content: "Which coaching institute did you join? Was it helpful?",
    answerId: "1",
    authorId: "5",
    author: mockUsers[4],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    content:
      "The point about not comparing with others' highlight reels is so important. Social media makes this worse.",
    answerId: "2",
    authorId: "1",
    author: mockUsers[0],
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
  },
  {
    id: "4",
    content: "How long did it take you to validate your idea? Any specific methods you'd recommend?",
    answerId: "3",
    authorId: "4",
    author: mockUsers[3],
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "5",
    content: "The gray rock method really works. It took me months to master it but it's worth it.",
    answerId: "4",
    authorId: "5",
    author: mockUsers[4],
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },
  {
    id: "6",
    content: "This is such a balanced perspective. Thanks for not being judgmental about either approach.",
    answerId: "5",
    authorId: "3",
    author: mockUsers[2],
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
  {
    id: "7",
    content: "Did you face any age discrimination during job interviews? That's my biggest worry.",
    answerId: "6",
    authorId: "1",
    author: mockUsers[0],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "8",
    content: "freeCodeCamp is amazing! I'm currently going through their JavaScript course.",
    answerId: "6",
    authorId: "4",
    author: mockUsers[3],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
]

export const mockTopics: Topic[] = [
  {
    id: "1",
    name: "Technology",
    description: "Programming, software development, AI, and tech trends",
    icon: "💻",
    questionCount: 1250,
    followerCount: 45000,
    color: "#3B82F6",
  },
  {
    id: "2",
    name: "Career & Education",
    description: "Job advice, career growth, education, and professional development",
    icon: "🎓",
    questionCount: 890,
    followerCount: 32000,
    color: "#10B981",
  },
  {
    id: "3",
    name: "Relationships",
    description: "Dating, marriage, family, and personal relationships",
    icon: "❤️",
    questionCount: 670,
    followerCount: 28000,
    color: "#EF4444",
  },
  {
    id: "4",
    name: "Health & Wellness",
    description: "Medical advice, fitness, mental health, and lifestyle",
    icon: "🏥",
    questionCount: 540,
    followerCount: 25000,
    color: "#06B6D4",
  },
  {
    id: "5",
    name: "Business & Entrepreneurship",
    description: "Startups, business strategy, entrepreneurship, and finance",
    icon: "💼",
    questionCount: 420,
    followerCount: 18000,
    color: "#8B5CF6",
  },
  {
    id: "6",
    name: "Travel & Culture",
    description: "Travel tips, cultural experiences, and global perspectives",
    icon: "✈️",
    questionCount: 380,
    followerCount: 22000,
    color: "#F59E0B",
  },
  {
    id: "7",
    name: "Science",
    description: "Physics, chemistry, biology, and scientific discoveries",
    icon: "🔬",
    questionCount: 310,
    followerCount: 15000,
    color: "#EC4899",
  },
  {
    id: "8",
    name: "Food & Cooking",
    description: "Recipes, cooking tips, restaurants, and culinary culture",
    icon: "🍳",
    questionCount: 290,
    followerCount: 20000,
    color: "#F97316",
  },
  {
    id: "9",
    name: "Personal Development",
    description: "Self-improvement, productivity, habits, and life skills",
    icon: "🌱",
    questionCount: 260,
    followerCount: 16000,
    color: "#84CC16",
  },
  {
    id: "10",
    name: "Arts & Entertainment",
    description: "Movies, music, books, art, and creative pursuits",
    icon: "🎨",
    questionCount: 240,
    followerCount: 14000,
    color: "#6366F1",
  },
]
